name: Node.js CI

on:
  pull_request:
    branches:
      - main # O la rama en la que quieras ejecutar las pruebas

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x" # Especifica la versión de Node.js

      - name: Install dependencies
        run: npm install

  run-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies # Esta tarea depende de que se complete 'install-dependencies'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Run tests
        run: npm test

  post-action:
    runs-on: ubuntu-latest
    needs: run-tests # Esta tarea depende de que se complete 'run-tests'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Notify success
        run: echo "All tasks completed successfully!"
